version: '3'
services:
  nim:
    build:
      context: .
      dockerfile: ./docker/nim/Dockerfile
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/root/project
    depends_on:
      - mysql
      - postgres

  mysql:
    #image: mariadb
    image: mysql:8.0
    platform: linux/x86_64
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: Password!
      TZ: Asia/Tokyo

  postgres:
    image: postgres
    tty: true
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password!
      TZ: Asia/Tokyo
    volumes:
      - ./db/pq:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  linux-compile:
    image: dockercore/golang-cross
    tty: true
    volumes:
      - .:/go/src

  windows-compile:
    image: golang:1.16
    tty: true
    volumes:
      - .:/go/src
  